# Generated by Django 4.2.7 on 2023-11-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devilx_home', '0009_alter_orders_order_date_alter_products_p_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=1000000.0, max_digits=10),
        ),
    ]
