# Generated by Django 4.2.6 on 2023-10-29 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosx_home', '0005_alter_orders_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 20, 55, 29, 676348, tzinfo=datetime.timezone.utc)),
        ),
    ]
